name: topsapp_env
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python>=3.10
 - affine
 - aiohttp  # only needed for manifest and swath download
 - asf_search>=3.0.4
 - boto3
 - cdsapi
 - cfgrib
 - cmake
 - cxx-compiler
 - cython
 - dask
 - dateparser
 - dem_stitcher>=2.3.0
 - ecmwf-api-client
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - gdal
 - geopandas
 - h5netcdf
 - h5py
 - herbie-data
 - hyp3lib>=1.7
 - ipykernel
 - isce2
 - isce3
 - jinja2
 - joblib
 - jsonschema==3.2.0
 - jupyter
 - lxml
 - matplotlib
 - netcdf4
 - notebook
 - numpy
 - pandas
 - papermill
 - pip
 - progressbar
 - pytest
 - pytest-cov
 - pytest-mock
 - rasterio
 - rioxarray
 - s3fs
 - setuptools
 - setuptools_scm
 - shapely
 - sysroot_linux-64
 - tqdm
 - pip:
   - git+https://github.com/dbekaert/RAiDER.git
