name: topsapp_env
channels:
 - conda-forge
dependencies:
 - python>=3.10,<3.11
 - pip
 - affine
 - asf_search>=5.0.0
 - boto3
 - dateparser
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - gdal
 - geopandas
 - hyp3lib>=1.7
 - ipykernel
 - isce2==2.6.2
 - jinja2
 - joblib
 - jsonschema==3.2.0
 - jupyter
 - lxml
 - matplotlib
 - netcdf4
 - notebook
 - numpy
 - pandas
 - pysolid
 - papermill
 - pytest
 - pytest-cov
 - pytest-mock
 - rasterio
 - rioxarray<0.14.0
 - xarray
 - setuptools
 - setuptools_scm
 - scipy>=1.10.1
 - shapely
 - tqdm
 - dem_stitcher>=2.4.0
 - aiohttp  # only needed for manifest and swath download
