name: topsapp_env
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python=3.8
 - isce2
 - jupyter
 - papermill
 - ipykernel
 - rasterio
 - shapely
 - dateparser
 - jinja2
 - numpy
 - matplotlib
 - netcdf4
 - fiona
 - geopandas
 - pip
 - boto3
 - asf_search>=3.0.4
 - pip:
   - dem_stitcher
   - tqdm
   - lxml
   - click
