name: topsapp_env
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python>=3.8
 - pip
 - asf_search>=3.0.4
 - boto3
 - dateparser
 - geopandas
 - hyp3lib>=1.7
 - isce2
 - jinja2
 - lxml
 - matplotlib
 - netcdf4
 - numpy
 - rasterio
 - shapely
 - tqdm
 # for testing and distribution
 - flake8
 - flake8-import-order
 - flake8-blind-except
 - flake8-builtins
 - ipykernel
 - jsonschema==3.2.0
 - jupyter
 - papermill
 - pytest
 - setuptools
 - setuptools_scm
 - pip:
   - git+https://github.com/ACCESS-Cloud-Based-InSAR/dem_stitcher.git
