name: topsapp_env
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python>=3.8
 - pip
 - asf_search>=3.0.4
 - boto3
 - dateparser
 - fiona
 - geopandas
 - ipykernel
 - isce2
 - jinja2
 - jsonschema==3.2.0
 - jupyter
 - matplotlib
 - netcdf4
 - numpy
 - papermill
 - pytest
 - rasterio
 - shapely
 - pip:
   - git+https://github.com/ACCESS-Cloud-Based-InSAR/dem_stitcher.git
   - tqdm
   - lxml
   - click
