name: topsapp_env
channels:
 - conda-forge
dependencies:
 - python>=3.9,<3.12
 - pip
 - affine
 - asf_search>=5.0.0
 - boto3
 - dask  # see https://github.com/unionai-oss/pandera/issues/1525
 - dateparser
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - fsspec
 - gdal
 - geopandas
 - hyp3lib>=3,<4
 - ipykernel
 - isce2==2.6.3
 - jinja2
 - joblib
 - jsonschema==3.2.0
 - jupyter
 - lxml
 - matplotlib
 - netcdf4
 - notebook
 - numpy<1.24
 - pandas
 - pysolid
 - papermill
 - pytest
 - pydantic
 - pytest-cov
 - pytest-mock
 - rasterio
 - rioxarray<0.14.0
 - xarray
 - scipy<1.10
 - setuptools
 - setuptools_scm
 - shapely
 - tqdm
 - dem_stitcher>=2.5.8
 - aiohttp  # only needed for manifest and swath download
 - tile_mate>=0.0.8
