name: topsapp_env
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python>=3.8
 - pip
 - asf_search>=3.0.4
 - boto3
 - dateparser
 - fiona
 - geopandas
 - hyp3lib>=1.7
 - ipykernel
 - isce2
 - jinja2
 - jsonschema==3.2.0
 - jupyter
 - lxml
 - matplotlib
 - netcdf4
 - numpy
 - papermill
 - pytest
 - rasterio
 - shapely
 - tqdm
 - pip:
   - git+https://github.com/ACCESS-Cloud-Based-InSAR/dem_stitcher.git
