name: build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo for Github Container Registry
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build, tag, and push image to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:${{ github.sha }}

      - name: Add test tag
        if: github.ref == 'refs/heads/dev'
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          dst: ghcr.io/${{ env.REPO }}:test

      - name: Add latest tag
        if: github.ref == 'refs/heads/main'
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          dst: ghcr.io/${{ env.REPO }}:latest
