name: build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  call-version-info-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-version-info.yml@main
    with:
      conda_env_name: topsapp_env

  call-docker-ghcr-workflow:
    needs: call-version-info-workflow
    uses: ASFHyP3/actions/.github/workflows/reusable-docker-ghcr.yml@main
    with:
      version_tag: ${{ needs.call-version-info-workflow.outputs.version_tag }}
      release_branch: main
      develop_branch: dev
      user: ${{ github.actor }}
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
