name: PyTest and Flake8

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: extractions/netrc@v1
        with:
          machine: urs.earthdata.nasa.gov
          username: ${{ secrets.EARTHDATA_USERNAME }}
          password: ${{ secrets.EARTHDATA_PASSWORD }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          activate-environment: topsapp_env
          environment-file: environment.yml

      - name: flake8
        shell: bash -l {0}
        run: |
          flake8 . --max-line-length=120 --import-order-style=pycharm --application-import-names isce2_topsapp --exclude=isce2_topsapp/packaging_utils/

      - name: Pytest in conda environment
        shell: bash -l {0}
        run: |
          python -m pip install .
          python -m ipykernel install --user --name topsapp_env
          pytest .
