name: PyTest

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/netrc@v1
        with:
          machine: urs.earthdata.nasa.gov
          username: ${{ secrets.EARTHDATA_USERNAME }}
          password: ${{ secrets.EARTHDATA_PASSWORD }}

      - uses: mamba-org/setup-micromamba@v1.8
        with:
          init-shell: bash
          environment-file: environment.yml
          extra-specs: >-
            python=${{ matrix.python-version }}

      - name: Pytest in conda environment
        shell: bash -l {0}
        run: |
          python -m pip install .
          python -m ipykernel install --user --name topsapp_env
          pytest .
